### ISSUE TITLE
Question: Best way to obtain second derivative of interpolations

### ISSUE THREAD

**Issue by jbiffl** [JuliaMath/FastChebInterp.jl#18]
I've just started using this package and so far it's all been going very well, but I'm curious if there's a recommended way to obtain the second derivative of the Chebyshev interpolations. 

Taking the first derivative is (as noted on the homepage here) about twice as fast using chebgradient than using ForwardDiff, but I've been getting the second derivative using `ForwardDiff.derivative.(x->stack(chebgradient.(fu,x))[2,:],x)` which seems clunky and makes me wonder if there's a better way. 

Thanks!

**Comment by stevengj** [comment]
You could use [TaylorDiff.jl](https://github.com/JuliaDiff/TaylorDiff.jl), which is similar to ForwardDiff.jl but is optimized to be faster for higher derivatives.

To do even better, you'd need something like the [`FastChebInterp.Jevaluate` function](https://github.com/JuliaMath/FastChebInterp.jl/blob/dc4902b09a480090f547ed8fbb06259bbf46de4c/src/eval.jl#L73-L134) (which computes the Jacobian, i.e. the first derivative), but for the 2nd derivative.   (This gets more expensive in higher dimensions, where it is a rank-3 tensor.)

**Comment by jbiffl** [comment]
Thanks for the reply! I'll look at TaylorDiff.jl and if I can get my head around the Jevaluate function I might try to implement a 2nd derivative equivalent.
