### ISSUE TITLE
Package does not seem to choose mathematically optimal nodes.

### ISSUE THREAD

**Issue by Flintro** [JuliaMath/FastChebInterp.jl#21]
The optimal node selection for approximation is:
cos(((2i-1) / (2 * n_nodes)) * π)

This package does not seem to select these optimal nodes when using the function chebpoints. For instance when approximating e^x with two nodes (linear approximation), the package chooses the two nodes to be the end points. This is obviously not optimal. The distance to the function can be smaller by selecting nodes to be interior, according to the above formula.

**Comment by Flintro** [comment]
Seems to choose the correct nodes with chebregression when using chebpoints so might be an issue on my end.

**Comment by stevengj** [comment]
chebpoints uses Chebyshev nodes $\cos(n \pi / N)$ for $n = 0 \ldots N$ (which indeed include the endpoints).  These allow us to evaluate the Chebyshev interpolant efficiently with an FFT (in particular, a type-I DCT), and are in some sense asymptotically optimal.

There indeed is another possible choice that does *not* include the endpoints, $\cos((2n - 1) \pi / 2N)$ for $n = 1 \ldots N$, corresponding to a type-II DCT, but this asymptotically has the same distribution and the same asymptotic convergence rate.  I'm not sure what you mean by "optimality" for a finite $N$, though — the goal is not to minimize the distance between the nodes and the evaluation points (which would lead to equally spaced points, which are terrible).

`chebregression` uses *all* the points you supply, which are chosen by the user, so I'm not sure what you mean by it "chooses the correct nodes".
